# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintUser',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reply', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'complaint_user',
                'managed': False,
            },
        ),
    ]
