# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=25)),
                ('ingredients', models.CharField(max_length=25)),
                ('rating', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
