# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
