# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomisation',
            fields=[
                ('product_customisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(db_column='Cake_Name', max_length=40)),
                ('flavour', models.CharField(max_length=25)),
                ('layer', models.CharField(max_length=40)),
                ('shape', models.CharField(db_column='Shape', max_length=40)),
                ('theme', models.CharField(max_length=40)),
                ('topper', models.CharField(max_length=40)),
                ('details', models.CharField(db_column='Details', max_length=40)),
                ('image', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=40)),
                ('wishes', models.CharField(db_column='Wishes', max_length=40)),
                ('amount', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'product_customisation',
                'managed': False,
            },
        ),
    ]
