# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=25)),
                ('voice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
    ]
