# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=40)),
                ('rating', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
