# Generated by Django 3.2.21 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
